[package]
name = "lambda_api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sha3 = "0.10.8"
advance_runner = {git = "https://github.com/dymchenkko/advance_runner"}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
serde_json = "1.0.107"
regex = "1.11.0"
dotenv = "0.15.0"

eigen-crypto-bls = { git = "https://github.com/Layr-Labs/eigensdk-rs", rev = "f69a9a943462f2a1635936ba5aa2f929ad718073", optional = true }
ark-serialize = "0.4.2"
sha2 = "0.10.8"

[features]
default = []
bls_signing = [
    "eigen-crypto-bls",
]
