[package]
name = "cartesi-coprocessor-operator"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
advance_runner = {git = "https://github.com/cartesi/coprocessor-advance-runner", rev = "a33f2fc1d16342006c2ec1d60622b75a2a44f086"}
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
async-stream = "0.3.6"
hex = "0.4"
serde_json = "1.0.132"
regex = "1.11.0"
signer-eigen = { path = "signer-eigen", optional = true }
rs-car-ipfs = { git = "https://github.com/zippiehq/rs-car-ipfs", rev = "00a6a00284bd307032054247bfd75380e10a55fa" }
ipfs-api-backend-hyper = { version = "0.6.0", features = ["with-send-sync"], default-features = false }
futures = "0.3"
cid = "0.8.6"
alloy-primitives = "0.8.25"
alloy-provider = "0.13.0"
alloy-rpc-types-eth = "0.13.0"
alloy-rlp = "0.3.12"
serde = "1.0.214"
base64 = "0.22.1"
rusqlite = { version = "0.25.3", features=["bundled"] }
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
bincode = "1.3.3"
futures-channel = "0.3.31"
reqwest = { version =  "0.12.9", features = ["multipart", "stream" ] }
chrono = "0.4.39"
cbor = "0.4.1"
sha2 = "0.10.8"
committable = { git = "https://github.com/EspressoSystems/commit" }
env_logger = "0.11.6"
log = "0.4.26"
ark-serialize = "0.5.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"
[features]
default = []
bls_signing = [
    "signer-eigen",
]
nitro_attestation = []
