[package]
name = "lambda_api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sha3 = "0.10.8"
advance_runner = {git = "https://github.com/dymchenkko/advance_runner"}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
serde_json = "1.0.107"