[package]
name = "signer-eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
eigen-crypto-bls = { git = "https://github.com/dymchenkko/eigensdk-rs", rev = "f9d6cb687584fac0a547cfc5df5bbccc91c3769a" }
hex = "0.4"
ark-serialize = "0.5.0"
