[package]
name = "signer-eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
eigen-crypto-bls = { git = "https://github.com/Layr-Labs/eigensdk-rs/", rev = "a7699ba5cdf873c2ecda7abf1dba26e966464b0c" }
hex = "0.4"
ark-serialize = "0.5.0"
