[package]
name = "signer-eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
eigen-crypto-bls = { git = "https://github.com/Layr-Labs/eigensdk-rs/", rev = "f69a9a943462f2a1635936ba5aa2f929ad718073" }
hex = "0.4"
ark-serialize = "0.4.2"
