[package]
name = "setup-operator"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-signer-local = { version = "0.5.3", default-features = false }
eigen-client-elcontracts = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
eigen-testing-utils = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
eigen-client-avsregistry = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
eigen-logging = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
eigen-crypto-bls = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
eigen-utils = { git = "https://github.com/stskeeps/eigensdk-rs", rev = "f52ed203e54280264b4ae08ed1e953eec34eddd3"}
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
alloy-primitives = "0.8.7"
clap = { version = "4.3.10", features = ["derive", "env", "string"] }
serde_json = "1.0.133"