[package]
name = "requests-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
hyper = { version = "0.14" , features=["full"]}
hex = "0.4"
async-std = { version = "1", features = ["attributes", "tokio1"] }
serde_json = "1.0.132"