name: operator

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  pull_request:
    branches:
      - '*'

permissions:
    id-token: write
    contents: read
    packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: |
                ghcr.io/zippiehq/cartesi-coprocessor-operator
          tags: |
                type=semver,pattern={{version}}
                type=ref,event=pr
                type=raw,value=testing,enable=${{ github.ref == format('refs/heads/{0}', 'testing') }}
                type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          labels: |
                org.opencontainers.image.title=Cartesi Coprocessor Operator
                org.opencontainers.image.description=Cartesi Coprocessor Operator

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 

    - name: Login to Github Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Depot ClI
      uses: depot/setup-action@v1
      env:
        DEPOT_TOKEN: ${{ secrets.DEPOT_API_TOKEN }}
  
    - name: Build and Push Docker Image with Depot
      uses: depot/bake-action@v1
      if:  ${{!startsWith(github.ref, 'refs/tags/') }}
      with:
        project: hs0gfs4l0l
        token: ${{ secrets.DEPOT_API_TOKEN }}
        files: |
          ./docker-bake.hcl
          ./docker-bake.platforms.hcl
          ${{ steps.meta.outputs.bake-file }}
        push: true  
